import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function ApprovePage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Approval queue</h1>
        <p className="text-sm text-slate-500 mt-1">
          Review tomorrow&apos;s drafts. Bulk-approve, edit individually, or reject.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Queue empty</CardTitle>
          <CardDescription>
            Drafts will appear here at 9 AM IST each morning, generated by the
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs mx-1">personalize-batch</code>
            workflow.
          </CardDescription>
        </CardHeader>
        <CardContent className="text-sm text-slate-600">
          <p>Coming in Phase 3.</p>
        </CardContent>
      </Card>
    </div>
  );
}
